<a href="https://colab.research.google.com/github/fathimathulfasna/Data-Analytics/blob/main/Numpy/Numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Numpy Package**

**numpy sub heading**


In [ ]:
import numpy as np

In [ ]:
arr1d = np.array( [1,2,3])
print(arr1d)

print(arr1d.shape)

type(arr1d)


[1 2 3]
(3,)


numpy.ndarray

In [ ]:
arr2d = np.array([ [1,2,3] , [2,3,4] ])
print(arr2d)

print(arr2d.shape)

type(arr2d)

[[1 2 3]
 [2 3 4]]
(2, 3)


numpy.ndarray

In [ ]:
arr3d = np.array( [ [ [1,4,5] , [5,7,9] , [9,7,6] ]])
print(arr3d)

print(arr3d.shape)

type(arr3d)

[[[1 4 5]
  [5 7 9]
  [9 7 6]]]
(1, 3, 3)


numpy.ndarray

In [ ]:
arr3dL =np.array([ [ [1,2,3] , [4,5,9] ] , [ [5,6,4] , [7,8,2] ] ])
print(arr3dL)

print(arr3dL.shape)

type(arr3dL)

[[[1 2 3]
  [4 5 9]]

 [[5 6 4]
  [7 8 2]]]
(2, 2, 3)


numpy.ndarray

In [ ]:
arr1d = np.array( [1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [ ]:
element = arr1d[2]
print(element)

3


**Slicing**

In [ ]:
slice = arr1d[1:4]
print(slice)

[2 3 4]


**Reshape array**

In [ ]:
reshaped = arr1d.reshape(5,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


**Iteration through array**

In [ ]:
arr = np.array([1,2,3,4,5])
for item in arr:
  print(item)

1
2
3
4
5


**To check dimension**


In [ ]:
print(arr3d.ndim)

3


**To check size of an array**

In [ ]:
print(arr1d.size)

5


In [ ]:
print(arr2d.size)

6


In [ ]:
print(arr3d.size)

9


**To check dtype**

In [ ]:
print(arr1d.dtype)

int64


In [ ]:
arr = np.array( [1,2,3,"abc",2.0,5.0])
print(arr)

['1' '2' '3' 'abc' '2.0' '5.0']


In [ ]:
print(arr.dtype)

<U32


**To change the dtype of an array**

In [ ]:
arr1 = np.array( [1,2,3,6,7,8] )
print (arr1)

print(arr1.dtype)

arr2 = arr1.astype('float64')

print(arr2)
print(arr2.dtype)

[1 2 3 6 7 8]
int64
[1. 2. 3. 6. 7. 8.]
float64


**To concatenate arrays in numpy**

In [ ]:
arr1 = np.array( [1,2,3] )
arr2 = np.array( [3,4,5] )

result = np.concatenate((arr1,arr2), axis=0)
print(result)


[1 2 3 3 4 5]


**To split arrays in numpy**

In [ ]:
import numpy as np
arr = np.array( [1,2,3,4,5,6] )
split = np.split(arr,3,axis=0)
print(split)

[array([1, 2]), array([3, 4]), array([5, 6])]


**To sort arrays in numpy**

In [ ]:
arr = np.array( [7,3,4,5,2,1])
sort = np.sort(arr)
print(sort)

[1 2 3 4 5 7]


**To check where specific condition satisfy in numpy**

In [ ]:
arr = np.array( [3,4,5,6,7,8])
where = np.where(arr >4)
print(where) # It returns Index positions

(array([2, 3, 4, 5]),)


**To filter a new array from arrays in numpy**

In [ ]:
arr = np.array( [ 1,2,5,2,3,6,8])
condition = arr > 4
filtered_arr = arr[condition] #creating a new array with elements greater than 5
print(filtered_arr)

[5 6 8]


**filtering arrays using boolean indexing**

In [ ]:
arr = np.array( [1,2,3])
x = [True,False,True]
newarr = arr[x]
print(newarr)

[1 3]


**Slicing rows and coloumns using index**

In [ ]:
arr = np.array( [ [1,2,3],
                  [1,2,4] ,
                  [5,6,7]])


In [ ]:
table = arr[1, :]
print(table)

[1 2 4]


In [ ]:
table = arr[:,1]
print(table)

[2 2 6]


In [ ]:
table = arr[:,2]
print(table)

[3 4 7]


In [ ]:
table = arr[0:2,:]
print(table)

[[1 2 3]
 [1 2 4]]


In [ ]:
table = arr[:,1:3]
print(table)

[[2 3]
 [2 4]
 [6 7]]


In [ ]:
table = arr[1:,:]
print(table)

[[1 2 4]
 [5 6 7]]


In [ ]:
table= arr[:,[0,2]]
print(table)

[[1 3]
 [1 4]
 [5 7]]


In [ ]:
table= arr[[0,2],:]
print(table)

[[1 2 3]
 [5 6 7]]


In [ ]:
table= arr[1:,[0,2]]
print(table)

[[1 4]
 [5 7]]


In [ ]:
table = arr[[0,2],1:]
print(table)

[[2 3]
 [6 7]]


In [ ]:
table=arr[1:,[0,1]]
print(table)

[[1 2]
 [5 6]]


In [ ]:
array = np.array( [ [1,2,3],
                  [4,5,6],
                  [7,8,9] ])
table=arr[[0,1],1:]
print(table)

[[2 3]
 [5 6]]


In [ ]:
table =arr[1,2]
print(table)

4


In [ ]:
import numpy as np
arr3dL =np.array([ [ [1,2,3] , [4,5,9] ] , [ [5,6,4] , [7,8,2] ] ])
print(arr3dL)


[[[1 2 3]
  [4 5 9]]

 [[5 6 4]
  [7 8 2]]]


In [ ]:
table = arr3dL[0,:,:]
print(table)

[[1 2 3]
 [4 5 9]]


In [ ]:
table = arr3dL[1,:,:]
print(table)

[[5 6 4]
 [7 8 2]]


In [ ]:
table =arr3dL[1,0,:]
print(table)

[5 6 4]


In [ ]:
table = arr3dL[0,1,:]
print(table)

[4 5 9]


In [ ]:
table = arr3dL[1,:,2]
print(table)

[4 2]


In [ ]:
table = arr3dL[0,:,1]
print(table)

[2 5]


#**uninitialized array in numpy**

In [ ]:
uninitialized_array =np.empty([5,3])
print(uninitialized_array)

[[4.71207172e-310 0.00000000e+000 6.94049486e-310]
 [6.94049486e-310 6.94049486e-310 6.94049486e-310]
 [5.09234030e+246 3.21142670e-322 4.71097874e-310]
 [6.94055850e-310 9.47751136e+170 1.63041663e-322]
 [4.71097881e-310 6.94055850e-310 7.90505033e-322]]


#**arrays initialized with zeros**

In [ ]:
a = np.zeros((3,3))
print(a)
print("---------------------------")
b = np.zeros((3,3),dtype=int)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#**arrays initialized with ones in numpy**

In [ ]:
c = np.ones((3,3))
print(c)

d = np.ones((3,3),dtype=int)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


#**numerical array ranges in numpy**

In [ ]:
array_with_range = np.arange(5)
print(array_with_range)

[0 1 2 3 4]


In [ ]:
array_range =np.arange(20,50,2)
print(array_range)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#**array from random numbers**

In [ ]:
random_array = np.random.random((4,3))
print(random_array)

[[0.76052398 0.75760324 0.14541377]
 [0.59683676 0.62282821 0.52493161]
 [0.9901892  0.59170478 0.37636929]
 [0.0141654  0.40469464 0.44460466]]


In [ ]:
random = np.random.randint(1,5)
print(random)

1


In [ ]:
random_array = np.random.randint(0,5,size=(2,3,4))
print(random_array)

[[[1 0 4 2]
  [3 3 1 4]
  [1 4 3 3]]

 [[3 2 3 2]
  [2 0 4 2]
  [0 2 0 2]]]


#**array from specified numbers**

In [ ]:
arr = np.full((3,3),20)
print(arr)

[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [ ]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#**basic statistics in numpy**

In [ ]:
arr = np.array ( [1,2,3,4,5] )
mean = np.mean(arr)
print(mean)


3.0


In [ ]:
arr = np.array( [1,2,3,4,5])
median = np.median(arr)
print("median: ",median)


median:  3.0


In [ ]:
arr = np.array( [1,2,3,4,5])
std_deviation = np.std(arr)
print("standered deviation:",std_deviation)

standered deviation: 1.4142135623730951


In [ ]:
arr = np.array( [1,2,3,4,5])
variance = np.var(arr)
print("variance: ",variance)

variance:  2.0


In [ ]:
arr = np.array( [1,2,3,4,5] )
minimum = np.min(arr)
print("minimum value : ",minimum)

maximum = np.max(arr)
print("maximum value : ",maximum)


minimum value :  1
maximum value :  5


In [ ]:
arr = np.array( [1,2,3,4,5])
sum =np.sum(arr)
print("sum : ",sum)

product = np.prod(arr)
print("product : ", product)

sum :  15
product :  120


#**Task 1**

In [ ]:
arr_1d = np.array( [1,2,3,4,5] )
print("1d array: ",arr_1d)
print("         ")

arr_2d = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
print("2d array: ",arr_2d)
print("         ")

arr_3d = np.array( [ [ [1,2], [3,4]], [[5,6],[7,8]], [[9,10], [11,12]]])
print("3d array: ",arr_3d)


1d array:  [1 2 3 4 5]
         
2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
         
3d array:  [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#1)3
x = arr_1d[2]
print(x)
#2)6
a = arr_2d[1,2]
print(a)

3
6


In [ ]:
#3)78
sum = np.sum(arr_3d)
print("sum : ",sum)

sum :  78


In [ ]:
#4) 6
x = arr_1d[0]
print(x)
y = arr_1d[4]
print(y)

row = x+y
sum_value = np.sum(row)
print("sum: ",sum_value)


1
5
sum:  6


In [ ]:
#5) 15
row = arr_2d[1,:]
print(row)
sum_value = np.sum(row)
print("sum: ",sum_value)


[4 5 6]
sum:  15


In [ ]:
#6) 6
arr = arr_3d[1,0,1]
print(arr)

6


In [ ]:
#7) 5
elements = np.size(arr_1d)
print(elements)

5


In [ ]:
#8) 28
row = arr_2d[:,0]
print(row)
product_value = np.prod(row)
print("product: ",product_value)

[1 4 7]
product:  28


In [ ]:
#9)

arr = arr_3d[1,:,:]
print(arr)
mean_value = np.mean(arr)
print("mean of second 2*2 array of arr_3d",mean_value)

[[5 6]
 [7 8]]
mean of second 2*2 array of arr_3d 6.5


In [ ]:
#10) 5
maximum = np.max(arr_1d)
print("maximum value: ",maximum)

maximum value:  5
